# TO REQUEST AND MAKE RESPONSE TO THE FILE
GET http://localhost:3000/routes

###

# TO REQUEST ONLY THE SPECIFIC FILE
GET http://localhost:3000/routes/:id

###

# TO EDIT THE SPECIFIC FILE
PUT http://localhost:3000/routes/1

{
    "bookname":"book sample edited 1",
    "publisher":"pubisher sample edited 1"
}

###

# TO POST ON THE EXISTING FILE
POST http://localhost:3000/routes

{
    "bookName": " ",
    "author": " ",
    "publisher": " ",
    "isbn": ,
    "datePublish": " "
}

